### ISSUE TITLE
Create mod for no death. Player takes no damage when hits objects

### ISSUE THREAD

**Issue by MasterMind11111** [MasterMan1234/BD#1]
i need to edit the damage variables in the assembly. Credits to amogguy#9204 on the official games discord for the idea

**Comment by arpan-lol** [comment]
Would you like me to create is as a separate file or a branch?

**Comment by arpan-lol** [comment]
@MasterMan1234

**Comment by arpan-lol** [comment]
creating a new file in the same branch for now.

**Comment by MasterMind11111** [comment]
ay bro

**Comment by MasterMind11111** [comment]
new file works, i knew you had posted this on discord previously a week ago i guess but i wanted to create a collective repo for all the mods. Thank you!
